stages:
  - Build app
  - Build image

variables:
  IMAGE_VERSION: $CI_BUILD_TAG

app build:
  stage: Build app
  image: trion/ng-cli
  script:
    # - npm install
    - npm ci --legacy-peer-deps
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main

docker build:
  stage: Build image
  image: docker:stable
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_BUILD_TAG
    - docker info
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_VERSION .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_VERSION
  only:
    - main
